=== avm-energo/coma/settings/check-board.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="check" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="signals" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type" type="xs:string" />
                                        <xs:element name="uint-set">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="item" maxOccurs="unbounded" type="xs:unsignedShort" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="start-addr" type="xs:unsignedShort" />
                                        <xs:element name="count" type="xs:unsignedShort" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="record" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="group" type="xs:string" />
                                        <xs:element name="record" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0">
                                                    <xs:element name="start-addr" minOccurs="0" type="xs:unsignedShort" />
                                                    <xs:element name="count" minOccurs="0" type="xs:unsignedShort" />
                                                    <xs:element name="toolTip" minOccurs="0" maxOccurs="1" type="xs:string" />
                                                    <xs:element name="string-array" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element maxOccurs="unbounded" name="item" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="desc" use="required" />
                                            </xs:complexType>
                                        </xs:element>    
                                        <xs:element name="start-addr"  minOccurs="0" type="xs:unsignedShort" />
                                        <xs:element name="count"  minOccurs="0" type="xs:unsignedShort" />
                                        <xs:element name="toolTip" minOccurs="0" maxOccurs="1" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="header" use="required" />
                                    <xs:attribute name="desc" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="header" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== avm-energo/coma/settings/old/check-8600.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Вибрации">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>200</item>
                <item>210</item>
            </uint-set>
            <start-addr>6040</start-addr>
            <count>36</count>
        </signals>
        <record header="Среднеквадратичные значения виброускорений, м/с2" desc="Датчик №%1">
            <group>200</group>
            <start-addr>6040</start-addr>
            <count>6</count>
        </record>
        <record header="Среднеквадратичные значения виброскоростей, мм/с" desc="Датчик №%1">
            <group>200</group>
            <start-addr>6046</start-addr>
            <count>6</count>
        </record>
        <record header="Среднеквадратичные значения виброперемещений, мкм" desc="Датчик №%1">
            <group>200</group>
            <start-addr>6052</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброускорения, м/с2/час" desc="Датчик №%1">
            <group>210</group>
            <start-addr>6058</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброскорости, мм/с/час" desc="Датчик №%1">
            <group>210</group>
            <start-addr>6064</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброперемещения, мкм/час" desc="Датчик №%1">
            <group>210</group>
            <start-addr>6070</start-addr>
            <count>6</count>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-8500.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>1000</start-addr>
            <count>29</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>10</item>
            </uint-set>
            <start-addr>1040</start-addr>
            <count>9</count>
        </signals>
        <record header="Параметры вводов">
            <group>1</group>
            <record desc="U ф.%1">
                <start-addr>1000</start-addr>
                <count>3</count>
                <toolTip>Фазное среднеквадратичное напряжение источника ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="U ср.">
                <start-addr>1003</start-addr>
                <toolTip>Среднее по фазам действующее напряжение источника</toolTip>
            </record>
            <record desc="I ф.%1">
                <start-addr>1004</start-addr>
                <count>3</count>
                <toolTip>Фазный среднеквадратичный ток ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="I ср.">
                <start-addr>1007</start-addr>
                <toolTip>Средний по фазам действующий ток</toolTip>
            </record>
            <record desc="Uи ф.%1">
                <start-addr>1008</start-addr>
                <count>3</count>
                <toolTip>Фазное среднеквадратичное напряжение нагрузки ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="Uи ср.">
                <start-addr>1011</start-addr>
                <toolTip>Среднее по фазам действующее напряжение нагрузки</toolTip>
            </record>
            <record desc="P ф.%1">
                <start-addr>1012</start-addr>
                <count>3</count>
                <toolTip>Истинная активная мощность фазы %1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="P суммарная">
                <start-addr>1015</start-addr>
                <toolTip>Истинная активная мощность суммарная</toolTip>
            </record>
            <record desc="Q ф.%1">
                <start-addr>1016</start-addr>
                <count>3</count>
                <toolTip>Реактивная мощность фазы %1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="Q суммарная">
                <start-addr>1019</start-addr>
                <toolTip>Реактивная мощность суммарная</toolTip>
            </record>
            <record desc="S ф.%1">
                <start-addr>1020</start-addr>
                <count>3</count>
                <toolTip>Полная (кажущаяся) мощность фазы %1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="S суммарная">
                <start-addr>1023</start-addr>
                <toolTip>Полная мощность суммарная</toolTip>
            </record>
            <record desc="cos ф.%1">
                <start-addr>1024</start-addr>
                <count>3</count>
                <toolTip>Коэффициент мощности фазы %1 (по S и P)</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="cos ср.">
                <start-addr>1027</start-addr>
                <toolTip>Коэффициент мощности средний (по S и P)</toolTip>
            </record>
            <record desc="Частота в сети, Гц">
                <start-addr>1028</start-addr>
            </record>
        </record>
        <record header="Параметры вводов">
            <group>10</group>
            <record desc="Tbo ф.%1">
                <start-addr>1040</start-addr>
                <count>3</count>
                <toolTip>Текущее время безоперационного простоя полюса ф.%1 выключателя</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="Iznos ф.%1">
                <start-addr>1043</start-addr>
                <count>3</count>
                <toolTip>Текущий электрический износ полюса ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="Resurs ф.%1">
                <start-addr>1046</start-addr>
                <count>3</count>
                <toolTip>Остаточный коммутационный ресурс ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-0022.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные
    мезонинная">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>4501</start-addr>
            <count>16</count>
        </signals>
        <record header="Текущее значение по каналу, °C" desc="Канал №%1">
            <group>1</group>
            <start-addr>4501</start-addr>
            <count>8</count>
        </record>
        <record header="Текущее значение по каналу, Ом" desc="Канал №%1">
            <group>1</group>
            <start-addr>4509</start-addr>
            <count>8</count>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-3400.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные
    базовая">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>101</start-addr>
            <count>2</count>
        </signals>
        <record header="Общие">
            <group>1</group>
            <record desc="Температура микроконтроллера, °С">
                <start-addr>101</start-addr>
            </record>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-0033.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные
    мезонинная">
        <signals>
            <type>M_BO</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>3002</start-addr>
            <count>1</count>
        </signals>
        <record header="Состояния входов">
            <group>1</group>
            <start-addr>3002</start-addr>
            <count>30</count>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-0021.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные
    мезонинная">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
                <item>10</item>
            </uint-set>
            <start-addr>2001</start-addr>
            <count>40</count>
        </signals>
        <record header="Значение по каналу, инж. единицы" desc="Канал №%1">
            <group>1</group>
            <start-addr>2001</start-addr>
            <count>8</count>
        </record>
        <record header="Текущее значение по каналу, мА" desc="Канал №%1">
            <group>1</group>
            <start-addr>2009</start-addr>
            <count>8</count>
        </record>
        <record header="Текущее значение по каналу, В" desc="Канал №%1">
            <group>1</group>
            <start-addr>2017</start-addr>
            <count>8</count>
        </record>
        <record header="Мин. значение по каналу, инж. единицы" desc="Канал №%1">
            <group>10</group>
            <start-addr>2025</start-addr>
            <count>8</count>
        </record>
        <record header="Макс. значение по каналу, инж. единицы" desc="Канал №%1">
            <group>10</group>
            <start-addr>2033</start-addr>
            <count>8</count>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-2200.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные
    базовая">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>101</start-addr>
            <count>2</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>4001</start-addr>
            <count>16</count>
        </signals>
        <record header="Общие">
            <group>1</group>
            <record desc="Температура микроконтроллера, °С">
                <start-addr>101</start-addr>
            </record>
        </record>
        <record header="Текущее значение по каналу, °C" desc="Канал №%1">
            <group>1</group>
            <start-addr>4001</start-addr>
            <count>8</count>
        </record>
        <record header="Текущее значение по каналу, Ом" desc="Канал №%1">
            <group>1</group>
            <start-addr>4009</start-addr>
            <count>8</count>
        </record>
    </check>
</root>

=== avm-energo/coma/settings/old/check-0084.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>101</start-addr>
            <count>2</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
                <item>10</item>
            </uint-set>
            <start-addr>1000</start-addr>
            <count>16</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
                <item>10</item>
            </uint-set>
            <start-addr>1100</start-addr>
            <count>16</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
                <item>10</item>
            </uint-set>
            <start-addr>2400</start-addr>
            <count>7</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>2420</start-addr>
            <count>14</count>
        </signals>
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
                <item>10</item>
            </uint-set>
            <start-addr>4501</start-addr>
            <count>2</count>
        </signals>
        <signals>
            <type>M_SP</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>3011</start-addr>
            <count>25</count>
        </signals>
        <record header="Общие">
            <group>1</group>
            <record desc="Температура микроконтроллера, °С">
                <start-addr>101</start-addr>
                <toolTip>Температура микроконтроллера, °С</toolTip>
            </record>
            <record desc="Tamb, °С">
                <start-addr>4501</start-addr>
                <toolTip>Температура окружающей среды, °С</toolTip>
            </record>
            <record desc="Частота, Гц">
                <start-addr>2400</start-addr>
                <toolTip>Частота, Гц</toolTip>
            </record>
        </record>
        <record header="Параметры вводов">
            <group>1</group>
            <record desc="U ф.%1, кВ">
                <start-addr>1000</start-addr>
                <count>3</count>
                <toolTip>Фазное действующее напряжение по 1-й гармонике ф.%1, кВ</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="I ф.%1, мА">
                <start-addr>1100</start-addr>
                <count>3</count>
                <toolTip>Действующее значение тока утечки ввода по 1-й гармонике ф.%1, мА</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="C1 ф.%1, пФ">
                <start-addr>2420</start-addr>
                <count>3</count>
                <toolTip>Емкость С1 ввода ф.%1, пФ</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="tgδ ф.%1, %">
                <start-addr>2423</start-addr>
                <count>3</count>
                <toolTip>Тангенс дельта ввода ф.%1, %</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="∆C ф.%1, %">
                <start-addr>2426</start-addr>
                <count>3</count>
                <toolTip>Приращение емкости С1 ввода ф.%1, %</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="∆tgδ ф.%1, %">
                <start-addr>2429</start-addr>
                <count>3</count>
                <toolTip>Приращение тангенса дельта ввода ф.%1, %</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
        </record>
        <record header="Параметры небаланса токов">
            <group>1</group>
            <record desc="Iunb, %">
                <start-addr>2432</start-addr>
                <toolTip>Действующее значение небаланса токов, %</toolTip>
            </record>
            <record desc="Phi_unb, град.">
                <start-addr>2433</start-addr>
                <toolTip>Угол небаланса токов относительно тока ф.А, град.</toolTip>
            </record>
        </record>
        <record header="Симметричные составляющие">
            <group>10</group>
            <record desc="U0, кВ">
                <start-addr>1011</start-addr>
                <toolTip>Напряжение нулевой последовательности, кВ</toolTip>
            </record>
            <record desc="U1, кВ">
                <start-addr>1012</start-addr>
                <toolTip>Напряжение прямой последовательности, кВ</toolTip>
            </record>
            <record desc="U2, кВ">
                <start-addr>1013</start-addr>
                <toolTip>Напряжение обратной последовательности, кВ</toolTip>
            </record>
            <record desc="I0, мА">
                <start-addr>1111</start-addr>
                <toolTip>Ток нулевой последовательности, мА</toolTip>
            </record>
            <record desc="I1, мА">
                <start-addr>1112</start-addr>
                <toolTip>Ток прямой последовательности, мА</toolTip>
            </record>
            <record desc="I2, мА">
                <start-addr>1113</start-addr>
                <toolTip>Ток обратной последовательности, мА</toolTip>
            </record>
        </record>
        <record header="Угловые значения">
            <group>10</group>
            <record desc="Phy_U ф.%1, град.">
                <start-addr>2401</start-addr>
                <count>3</count>
                <toolTip>Угол по напряжению ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
            <record desc="Phy_I ф.%1, град.">
                <start-addr>2404</start-addr>
                <count>3</count>
                <toolTip>Угол по току ф.%1</toolTip>
                <string-array>
                    <item>A</item>
                    <item>B</item>
                    <item>C</item>
                </string-array>
            </record>
        </record>
        <record header="Коэффициенты несимметрии">
            <group>10</group>
            <record desc="KuI1, %">
                <start-addr>1114</start-addr>
                <toolTip>Коэффициент несимметрии тока по нулевой последовательности, %</toolTip>
            </record>
            <record desc="KuI2, %">
                <start-addr>1115</start-addr>
                <toolTip>Коэффициент несимметрии тока по обратной последовательности, %</toolTip>
            </record>
            <record desc="KuU1, %">
                <start-addr>1014</start-addr>
                <toolTip>Коэффициент несимметрии напряжения по нулевой последовательности, %</toolTip>
            </record>
            <record desc="KuU2, %">
                <start-addr>1015</start-addr>
                <toolTip>Коэффициент несимметрии напряжения по обратной последовательности, %</toolTip>
            </record>
        </record>
        <record header="Температура">
            <group>10</group>
            <record desc="Ramb, Ом">
                <start-addr>4502</start-addr>
                <toolTip>Сопротивление датчика, Ом</toolTip>
            </record>
        </record>
    </check>
</root>
