=== avm-energo/coma/settings/old/check.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="check">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="map">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="xs:string" />
                                                    <xs:element name="value" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== avm-energo/coma/settings/old/check.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root  [
    <!ENTITY groupEmpty "0">  
    <!ENTITY groupMain "1"> 
    <!ENTITY groupAdditional "10"> 
    <!ENTITY groupRmsValues "200"> 
    <!ENTITY groupChangeRate "210"> 
    <!ENTITY groupHarm1 "310"> 
    <!ENTITY groupHarm1A "311"> 
    <!ENTITY groupHarm1B "312"> 
    <!ENTITY groupHarm1C "313"> 
    <!ENTITY groupHarm2 "320"> 
]> 
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check.xsd">
    
    <check>
        <map name="categories">
            <item>
                <key>&groupEmpty;</key>
                <value>Пустая группа</value>
            </item>
            <item>
                <key>&groupMain;</key>
                <value>Основные</value>
            </item>
            <item>
                <key>&groupAdditional;</key>
                <value>Дополнительные</value>
            </item>
            <item>
                <key>&groupRmsValues;</key>
                <value>Среднеквадратичные значения</value>
            </item>
            <item>
                <key>&groupChangeRate;</key>
                <value>Скорости изменения</value>
            </item>
            <item>
                <key>&groupHarm1;</key>
                <value>Гармоники первой тройки</value>
            </item>
            <item>
                <key>&groupHarm1A;</key>
                <value>Гармоники фазы A</value>
            </item>
            <item>
                <key>&groupHarm1B;</key>
                <value>Гармоники фазы B</value>
            </item>
            <item>
                <key>&groupHarm1C;</key>
                <value>Гармоники фазы C</value>
            </item>
            <item>
                <key>&groupHarm2;</key>
                <value>Гармоники второй тройки</value>
            </item>
        </map>
    </check>    
</root>
