=== avm-energo/coma/settings/old/device-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="modules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="module">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="1"	maxOccurs="1" name="name" type="xs:string" />
							<xs:element minOccurs="1" maxOccurs="1" name="version" type="xs:string" />
							<xs:element name="resources">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="alarm">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="string-array">
														<xs:complexType>
															<xs:sequence>
																<xs:element maxOccurs="unbounded" name="item" type="xs:string" />
															</xs:sequence>
															<xs:attribute name="name" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
													<xs:element minOccurs="0" maxOccurs="1" name="quint128">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element minOccurs="1" maxOccurs="2" name="quint32">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="color" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" name="journal">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="0"	maxOccurs="1" name="quint32">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:unsignedShort">
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="string-array">
														<xs:complexType>
															<xs:sequence>
																<xs:element maxOccurs="unbounded" name="item" type="xs:string" />
															</xs:sequence>
															<xs:attribute name="name" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="modbus">
											<xs:complexType>
												<xs:sequence>
													<xs:choice maxOccurs="unbounded">
														<xs:element maxOccurs="unbounded" name="group">
															<xs:complexType>
																<xs:sequence>
																	<xs:element minOccurs="1" maxOccurs="1" name="function" type="xs:unsignedByte" />
																	<xs:element minOccurs="1" maxOccurs="1" name="type" type="xs:string" />
																	<xs:element minOccurs="1" maxOccurs="1" name="start-addr" type="xs:unsignedShort" />
																	<xs:element minOccurs="1" maxOccurs="1" name="count" type="xs:unsignedByte" />
																</xs:sequence>
																<xs:attribute name="id" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
														<xs:element maxOccurs="unbounded" name="register">
															<xs:complexType>
																<xs:sequence>
																	<xs:element minOccurs="1" maxOccurs="1" name="function" type="xs:unsignedByte" />
																	<xs:element minOccurs="1" maxOccurs="1" name="type" type="xs:string" />
																	<xs:element minOccurs="1" maxOccurs="1" name="start-addr" type="xs:unsignedShort" />
																</xs:sequence>
																<xs:attribute name="id" type="xs:string" use="required" />
															</xs:complexType>
														</xs:element>
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="protocom">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="group">
														<xs:complexType>
															<xs:sequence>
																<xs:element  minOccurs="1" maxOccurs="1" name="start-addr" type="xs:unsignedShort" />
																<xs:element  minOccurs="1" maxOccurs="1" name="count" type="xs:unsignedByte" />
																<xs:element  minOccurs="1" maxOccurs="1" name="block" type="xs:unsignedByte" />
															</xs:sequence>
															<xs:attribute name="id" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="iec60870" type="xs:string" />
										<xs:element name="s2files">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="record">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="id" type="xs:unsignedShort" />
																<xs:element name="defaultValue" type="xs:string" />
																<xs:element  minOccurs="0" maxOccurs="1" name="visibility" type="xs:boolean" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="mtypeb" type="xs:string" use="required" />
						<xs:attribute name="mtypem" type="xs:unsignedByte" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== avm-energo/coma/settings/old/avtuk-8081.xml
<?xml version="1.0" encoding="utf-8"?>
<modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="device-schema.xsd">
  <!--Здесь мы описываем текущий модуль, обязательно указать mtypeb и mtypem-->
  <module mtypeb="80" mtypem="81">
    <!--Здесь указано название модуля-->
    <name>AVTUK-8081</name>
    <version>2.5-0002</version>
    <!--Дальше идет всё, что несредственно относится к модулю-->
    <resources>
      <!--Описываем сигнализацию, имя обязательно-->

      <!--Описываем протокол Modbus-->
      <modbus>
      </modbus>

      <!--Описываем протокол Protocom-->
      <!--Описываем протокол Protocom-->
      <protocom>
        <!--Protocom состоит только из групп-->
        <group>
          <start-addr>101</start-addr>
          <count>2</count>
          <block>0</block>
        </group>
        <group>
          <start-addr>1400</start-addr>
          <count>11</count>
          <block>2</block>
        </group>
        <group>
          <start-addr>1420</start-addr>
          <count>8</count>
          <block>4</block>
        </group>
        <group>
          <start-addr>1028</start-addr>
          <count>61</count>
          <block>25</block>
        </group>
        <group>
          <start-addr>1089</start-addr>
          <count>61</count>
          <block>35</block>
        </group>
        <group>
          <start-addr>1150</start-addr>
          <count>61</count>
          <block>45</block>
        </group>
        <group>
          <start-addr>2100</start-addr>
          <count>11</count>
          <block>3</block>
        </group>
        <group>
          <start-addr>2120</start-addr>
          <count>8</count>
          <block>6</block>
        </group>
        <group>
          <start-addr>1428</start-addr>
          <count>61</count>
          <block>27</block>
        </group>
        <group>
          <start-addr>1489</start-addr>
          <count>61</count>
          <block>37</block>
        </group>
        <group>
          <start-addr>1550</start-addr>
          <count>61</count>
          <block>47</block>
        </group>

        <group id="alarmModule">
          <start-addr>3011</start-addr>
          <count>25</count>
          <block>100</block>
        </group>      
      </protocom>
      <iec60870>
        
      </iec60870>

      <s2files>
				<record>
					<id>3</id>
					<defaultValue>1</defaultValue>
				</record>
				<record>
					<id>4</id>
					<defaultValue>205</defaultValue>
				</record>
				<record>
					<id>5</id>
					<defaultValue>5</defaultValue>
				</record>
				<record>
					<id>6</id>
					<defaultValue>15</defaultValue>
				</record>
				<record>
					<id>7</id>
					<defaultValue>10</defaultValue>
				</record>
				<record>
					<id>8</id>
					<defaultValue>20</defaultValue>
				</record>
				<record>
					<id>9</id>
					<defaultValue>12</defaultValue>
				</record>
				<record>
					<id>10</id>
					<defaultValue>8</defaultValue>
				</record>
        <record>
					<id>1001</id>
					<defaultValue>1</defaultValue>
				</record>
        <record>
					<id>1002</id>
					<defaultValue>256</defaultValue>
				</record>
				<record>
					<id>1003</id>
					<defaultValue>100</defaultValue>
				</record>
        <record>
					<id>1004</id>
					<defaultValue>3</defaultValue>
				</record>
        <record>
					<id>1005</id>
					<defaultValue>7</defaultValue>
				</record>
				<record>
					<id>1006</id>
					<defaultValue>500</defaultValue>
				</record>
        <record>
					<id>1007</id>
					<defaultValue>220</defaultValue>
				</record>
        <record>
					<id>1008</id>
					<defaultValue>600,600,600,1000,1000,1000</defaultValue>
				</record>
        <record>
					<id>1009</id>
					<defaultValue>5,5,5,5,5,5</defaultValue>
				</record>
        <record>
					<id>1010</id>
					<defaultValue>2</defaultValue>
				</record>
        <record>
					<id>1011</id>
					<defaultValue>2</defaultValue>
				</record>
				<record>
					<id>1012</id>
					<defaultValue>0.5</defaultValue>
				</record>
				<record>
					<id>1050</id>
					<defaultValue>100.0</defaultValue>
				</record>
        <record>
					<id>1051</id>
					<defaultValue>100.0</defaultValue>
				</record>
        <record>
					<id>1054</id>
					<defaultValue>0</defaultValue>
				</record>
        <record>
					<id>1055</id>
					<defaultValue>0</defaultValue>
				</record>
			</s2files>
    </resources>
  </module>
</modules>
