=== avm-energo/coma/settings/old/s2files.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="s2files">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="map">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="item">
								<xs:complexType>
									<xs:sequence>
											<xs:element name="key" type="xs:unsignedShort" />
											<xs:element name="value" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" name="record">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:unsignedShort" />
							<xs:element minOccurs="0" maxOccurs="1" name="type" type="xs:string" />
							<xs:element minOccurs="0" maxOccurs="1" name="defaultValue" type="xs:string" />
							<xs:element minOccurs="0" name="widget">
								<xs:complexType>
									<xs:sequence>
										<xs:choice maxOccurs="unbounded">
											<xs:element name="type" type="xs:string" />
											<xs:element name="group" type="xs:unsignedShort" />
											<xs:element name="field" type="xs:string" />
											<xs:element name="string" type="xs:string" />
											<xs:element name="toolTip" type="xs:string" />
											<xs:element name="min" type="xs:int" />
											<xs:element name="max" type="xs:int" />
											<xs:element name="decimals" type="xs:unsignedByte" />
											<xs:element name="string-array">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="item" type="xs:string" />
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="count" type="xs:unsignedByte" />
											<xs:element name="parent" type="xs:unsignedShort" />
										</xs:choice>
									</xs:sequence>
									<xs:attribute name="class" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== avm-energo/coma/settings/old/config-3300.xml
<?xml version="1.0" encoding="utf-8"?>
<s2files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2files.xsd">
    <record>
        <id>205</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>211</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>212</id>
        <defaultValue>2</defaultValue>
    </record>
</s2files>

=== avm-energo/coma/settings/old/config-0035.xml
<?xml version="1.0" encoding="utf-8"?>
<s2files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2files.xsd">
    <record>
        <id>421</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>422</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>423</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>424</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>425</id>
        <defaultValue>0</defaultValue>
    </record>
    <record>
        <id>427</id>
        <defaultValue>0</defaultValue>
        <widget>
			<type>QComboBoxGroup</type>
			<count>4</count>
		</widget>
    </record>
    <record>
        <id>428</id>
        <defaultValue>0</defaultValue>
        <widget>
			<type>QComboBoxGroup</type>
			<count>4</count>
		</widget>
    </record>
</s2files>

=== avm-energo/coma/settings/old/config-2100.xml
<?xml version="1.0" encoding="utf-8"?>
<s2files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2files.xsd">
    <record>
        <id>101</id>
        <defaultValue>1,1,1,1,1,1,1,1</defaultValue>
    </record>
    <record>
        <id>102</id>
        <defaultValue>4,4,4,4,4,4,4,4</defaultValue>
    </record>
    <record>
        <id>103</id>
        <defaultValue>20,20,20,20,20,20,20,20</defaultValue>
    </record>
    <record>
        <id>104</id>
        <defaultValue></defaultValue>
    </record>
    <record>
        <id>105</id>
        <defaultValue>1000,1000,1000,1000,1000,1000,1000,1000</defaultValue>
    </record>
    <record>
        <id>106</id>
        <defaultValue>10,10,10,10,10,10,10,10</defaultValue>
    </record>
    <record>
        <id>107</id>
        <defaultValue>50,50,50,50,50,50,50,50</defaultValue>
    </record>
    <record>
        <id>108</id>
        <defaultValue>950,950,950,950,950,950,950,950</defaultValue>
    </record>
    <record>
        <id>109</id>
        <defaultValue>990,990,990,990,990,990,990,990</defaultValue>
    </record>
    <record>
        <id>111</id>
        <defaultValue></defaultValue>
    </record>
    <record>
        <id>112</id>
        <defaultValue>2</defaultValue>
    </record>
    <record>
        <id>113</id>
        <defaultValue>16</defaultValue>
    </record>
    <record>
        <id>114</id>
        <defaultValue>5</defaultValue>
    </record>
    <record>
        <id>115</id>
        <defaultValue>5</defaultValue>
    </record>
    <record>
        <id>116</id>
        <defaultValue></defaultValue>
    </record>
    <record>
        <id>117</id>
        <defaultValue></defaultValue>
    </record>
    <record>
        <id>118</id>
        <defaultValue></defaultValue>
    </record>
</s2files>
